services:
  app:
    build: .
    restart: always
    deploy:
      replicas: 3   # Horizontal scaling: 3 app containers
    ports:
      - "8002:8000"
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - internal


networks:
  internal: