name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Scalibility_Practice/**'
  workflow_dispatch:
    inputs: {} 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Get short commit SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Scalibility_Practice
        push: ${{ github.event_name == 'push' }}
        tags: ${{ secrets.DOCKER_USERNAME }}/query-api:latest,${{ secrets.DOCKER_USERNAME }}/query-api:${{ env.SHORT_SHA }}

    # - name: Update docker-compose.yml with commit tag
    #   run: |
    #     sed -i "s|rag-system:latest|rag-system:${SHORT_SHA}|g" ./RAG_System/compose.yaml
